# Generated by Django 4.0.4 on 2022-04-18 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomParking', models.CharField(max_length=50)),
                ('nbrPlaces', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('numPay', models.IntegerField()),
                ('typePay', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numPlace', models.IntegerField()),
                ('status', models.BooleanField()),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.parking')),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numMatricule', models.CharField(max_length=10)),
                ('marque', models.CharField(max_length=25)),
                ('modele', models.CharField(max_length=25)),
                ('couleur', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateN', models.DateField()),
                ('lieuN', models.CharField(max_length=50)),
                ('numPermis', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stationnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heurD', models.TimeField()),
                ('heurF', models.TimeField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.place')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.voiture')),
            ],
        ),
    ]
