# Generated by Django 4.0.4 on 2022-04-18 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationnement',
            name='voiture',
        ),
        migrations.AddField(
            model_name='stationnement',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='client.utilisateur'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Voiture',
        ),
    ]
