# Generated by Django 4.0.4 on 2022-04-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_stationnement_voiture_stationnement_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='dateN',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='lieuN',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='numTel',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
