# Generated by Django 4.0.4 on 2022-04-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_utilisateur_daten_remove_utilisateur_lieun_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationnement',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stationnement',
            name='heurD',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stationnement',
            name='heurF',
            field=models.TimeField(blank=True),
        ),
    ]
