# Generated by Django 4.0.4 on 2022-04-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_stationnement_heurf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stationnement',
            old_name='date',
            new_name='dateD',
        ),
        migrations.RemoveField(
            model_name='stationnement',
            name='heurD',
        ),
        migrations.RemoveField(
            model_name='stationnement',
            name='heurF',
        ),
        migrations.AddField(
            model_name='stationnement',
            name='dateF',
            field=models.DateField(blank=True, null=True),
        ),
    ]
