# Generated by Django 4.0.4 on 2022-04-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_rename_date_stationnement_dated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationnement',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
