# Generated by Django 4.0.4 on 2022-04-19 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_stationnement_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationnement',
            name='date',
        ),
    ]
