# Generated by Django 4.0.4 on 2022-04-20 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_stationnement_dated_alter_stationnement_datef'),
    ]

    operations = [
        migrations.AddField(
            model_name='payement',
            name='stat',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='client.stationnement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payement',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
