# Generated by Django 4.0.4 on 2022-04-21 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_payement_stat_alter_payement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payement',
            name='stat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.stationnement'),
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numA', models.IntegerField()),
                ('dateD', models.DateTimeField(auto_now=True)),
                ('dateF', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='payement',
            name='abonnement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.abonnement'),
        ),
    ]
